title: Tae (Terry) Min Seung
#logo
description: Entry-level data analytics professional; highly motivated individual who has completed and continuing to further education in programming languages and data analysis skills to pivot a career into the field of data analytics and data science; created a working portfolio to demonstrate proficiency in data analytics that is hosted on Github
#show_downloads:
theme: jekyll-theme-minimal
